ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

ARG ROS_DISTRO=jazzy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y
RUN apt-get install build-essential make cmake wget zip unzip python3-pip python3-dev python-is-python3 sudo vim git libhidapi-dev tmux usbutils screen picocom -y

## install ros2 base deps

RUN locale && \
	apt install locales -y && \
	locale-gen en_US en_US.UTF-8 && \
	update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
	export LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

RUN apt install software-properties-common -y && add-apt-repository universe -y && \
	apt update && apt install curl -y

RUN ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') && \
	curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
	dpkg -i /tmp/ros2-apt-source.deb

RUN apt update && apt install ros-dev-tools ros-$ROS_DISTRO-ros-base -y

## install micro_ros_setup and dependencies

WORKDIR /opt/uros_ws

RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
    &&  git clone -b $ROS_DISTRO https://github.com/micro-ROS/micro_ros_setup.git src/micro_ros_setup \
    &&  git clone -b $ROS_DISTRO https://github.com/micro-ROS/micro_ros_msgs src/micro_ros_msgs \
    &&  git clone -b $ROS_DISTRO https://github.com/micro-ROS/micro-ROS-Agent src/micro-ROS-Agent \
    &&  . /opt/ros/$ROS_DISTRO/setup.sh \
    &&  apt update \
    &&  apt install -y rsync python3-pip python3-nose clang-format pyflakes3 python3-mypy python3-pytest-mock gperf ros-$ROS_DISTRO-osrf-testing-tools-cpp python3-lttng ros-$ROS_DISTRO-mimick-vendor python3-babeltrace \
    &&  rosdep init \
    &&  rosdep update --rosdistro $ROS_DISTRO \
    &&  rosdep install --from-paths src --ignore-src -y \
    &&  colcon build \
    &&  . install/local_setup.sh \
    &&  rm -rf log/ build/

ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ENV MICROROS_DISABLE_SHM=1

COPY disable_fastdds_shm.xml disable_fastdds_shm_localhost_only.xml /tmp/

RUN echo ". /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
RUN echo ". /opt/uros_ws/install/setup.bash" >> ~/.bashrc

COPY ./micro-ros-agent-entrypoint.sh /micro-ros-agent-entrypoint.sh

WORKDIR /opt
RUN git clone --recurse-submodules --shallow-submodules --depth 1 -j 4 https://github.com/alexchenfeng/coralmicro.git
WORKDIR /opt/coralmicro

RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL=/usr/local/bin sh
RUN uv venv --system-site-packages && \
	. .venv/bin/activate && \
	git pull && git submodule update --recursive --force && \
	bash setup.sh && \
	# ensure build success
	bash build.sh && \
	rm -rf build

ENV ROS_DISTRO=${ROS_DISTRO}

ENV ROS_DISTRO=${ROS_DISTRO}

# Arduino coral core install

RUN cd /tmp && \
	wget https://github.com/arduino/arduino-cli/releases/download/v1.5.1/arduino-cli_1.5.1_Linux_ARM64.tar.gz && \
	tar xf arduino-cli_1.5.1_Linux_ARM64.tar.gz && \
	mv arduino-cli /usr/local/bin/ && \
	rm -fv arduino-cli_1.5.1_Linux_ARM64.tar.gz LICENSE.txt

RUN arduino-cli config init && arduino-cli core update-index

## build arduino core and flashtool

ENV TEMP_ARDUINO_CORE_DIR=/tmp/arduino-core-build
ENV TEMP_ARDUINO_FLASHTOOL_DIR=/tmp/flashtool-build
ENV TEMP_MANIFEST_DIR=/tmp/arduino-manifest
ARG ARDUINO_CORE_MANIFEST_VERSION=1.0.1

RUN . .venv/bin/activate \
	&& python3 arduino/package.py --core --output_dir $TEMP_ARDUINO_CORE_DIR  \
	&& python3 arduino/package.py --flashtool --output_dir $TEMP_ARDUINO_FLASHTOOL_DIR \
	&& python3 arduino/package.py --manifest --manifest_revision $ARDUINO_CORE_MANIFEST_VERSION  --output_dir $TEMP_MANIFEST_DIR  \
	&& cd $TEMP_ARDUINO_CORE_DIR && tar xf * \
	&& cd $TEMP_ARDUINO_FLASHTOOL_DIR && tar xf * \
 	&& mkdir -pv ~/.arduino15/packages/coral/hardware/coral_micro/${ARDUINO_CORE_MANIFEST_VERSION} \
	&& mkdir -pv ~/.arduino15/packages/coral/tools/arm-none-eabi-gcc \
	&& mkdir -pv ~/.arduino15/packages/coral/tools/flashtool/${ARDUINO_CORE_MANIFEST_VERSION} \
	&& cd ~/.arduino15/packages/coral/hardware/coral_micro/${ARDUINO_CORE_MANIFEST_VERSION} \
	&& cp -a $TEMP_ARDUINO_CORE_DIR/*/* ./ \
	&& cp -v $TEMP_MANIFEST_DIR/* ./ \
	&& cd ~/.arduino15/packages/coral/tools/arm-none-eabi-gcc \
	&& ln -sv /opt/coralmicro/third_party/toolchain/gcc-arm-none-eabi ./9-2020q2 \
	&& cd ~/.arduino15/packages/coral/tools/flashtool/${ARDUINO_CORE_MANIFEST_VERSION} \
        && cp -v $TEMP_ARDUINO_FLASHTOOL_DIR/*/flashtool ./ \
	&& rm -rf ${TEMP_ARDUINO_CORE_DIR} ${TEMP_ARDUINO_FLASHTOOL_DIR} ${TEMP_MANIFEST_DIR}

RUN arduino-cli core list && arduino-cli lib list

## install arduino micro ros lib

RUN mkdir -pv ~/Arduino/libraries && \
	cd ~/Arduino/libraries && \
	ln -sv /opt/coralmicro/libs/micro_ros_arduino ./ && \
	cd ~/ && \
	arduino-cli lib list

RUN arduino-cli completion bash > ~/.arduino_cli_completion.sh && \
	apt update && apt install bash-completion -y && \
	echo '[[ -r /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion' >> ~/.bashrc && \
	echo "source  ~/.arduino_cli_completion.sh" >> ~/.bashrc

ENTRYPOINT ["/bin/sh", "/micro-ros-agent-entrypoint.sh"]
CMD ["--help"]
