name=ZenohPico
version=1.10.1
author=ZettaScale Technology
maintainer=Google Coral <coral-support@google.com>
sentence=Eclipse Zenoh-Pico client library for Coral Dev Board Micro
paragraph=Zenoh-Pico is a lightweight client implementation of Eclipse Zenoh for microcontrollers. It provides publish/subscribe and query/reply communications over TCP and Wi-Fi/Ethernet.
category=Communication
url=https://zenoh.io
architectures=coral_micro_wifi,coral_micro_poe,coral_micro
precompiled=true
includes=ZenohPico.h,zenoh-pico.h
